server:
  port: 9000
spring:
  application:
    name: eureka-business-server
  shardingsphere:
    props:
      sql:
        #设置sql是否展示
        show: true
    datasource:
      #数据库名称（可以与数据库中的库名不一致）
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/entry_task?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      tables:
        tab_account:
          actual-data-nodes: master.tab_account_$->{0..9}
          table-strategy:
            #根据id取模决定去那个表
            inline:
              sharding-column: account_name
              algorithm-expression: tab_account_$->{Long.parseLong(account_name) % 10}
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

##mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka/
#  instance:
#    ip-address: 127.0.0.1
#    instance-id: bussiness-server9000
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2

